export const subjectsOptions = [
  'Algebra',
  'Art',
  'Astronomy',
  'Biology',
  'Chemistry',
  'Computer science',
  'Dutch language',
  'Ecology',
  'English language',
  'Geography',
  'Geometry',
  'History',
  'Literature',
  'Literary reading',
  'Mathematics',
  'Music',
  'Native language',
  'Physical education',
  'Physics',
  'Russian language',
  'Sociology',
  'Technology',
  'The world',
]
